---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.9.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: flake8
        args:
          - "--max-line-length=127"
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: name-tests-test
        exclude: tests/(common.py|util.py|(helpers)/(.+).py)
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--remove-import"
          - "from __future__ import absolute_import"
          - "--remove-import"
          - "from __future__ import unicode_literals"
